#!/bin/bash

set -o posix

#testDshMakeAppRunsWithErrorIfAnAppPackageDoesNotExistAtPATH_TO_APP_PACKAGE()
#testDshMakeAppRunsWithErrorIfAnAppAlreadyExistsWhoseNameMatchesTheNameOfTheAppToBeMadeAndREPLACE_EXISTING_APPIsNotSetTo_replace()
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_css_Directory
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_js_Directory
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_DynamicOutput_Directory
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_Responses_Script
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_Requests_Script
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_OutputComponents_Script
#testDshMakeAppRunsWithErrorIfTheAppPackageDoesNotContainA_Config_Script
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_app_name_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineAbug_contact_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_config_locked_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_dependencies_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_description_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_developers_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_development_port_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_documentation_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_domain_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_license_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_version_Setting
#testDshMakeAppRunsWithErrorIfTheAppPackagesConfigSHDoesNotDefineA_version_date_Setting
#testDshMakeAppCreatesAHiddenCopyOfTheAppPackagesConfigSHInTheNewAppsDirectory()

