<?php

$appComponentsFactory->buildGlobalResponse(
    'GlobalResponse',
    0,
    $appComponentsFactory->buildStandardUITemplate(
        'StandardUITemplate',
        'Components',
        0,
        $appComponentsFactory->buildDynamicOutputComponent(
            'DynamicOutputComponent',
            'Components',
            0,
            'DDMSTestApp',
            'Duplicate.php'
        ),
    ),
    $appComponentsFactory->buildDynamicOutputComponent(
        'Title',
        'Components',
        0,
        'DDMSTestApp',
        'Title.php'
    ),
    $appComponentsFactory->buildDynamicOutputComponent(
        'Meta',
        'Components',
        1,
        'DDMSTestApp',
        'Meta.html'
    ),
    $appComponentsFactory->buildDynamicOutputComponent(
        'Meta',
        'Components',
        1,
        'DDMSTestApp',
        'Stylesheets.php'
    ),
    $appComponentsFactory->buildDynamicOutputComponent(
        'Scripts',
        'Components',
        1,
        'DDMSTestApp',
        'Scripts.php'
    ),
);

