#!/bin/bash
# APP_NAME | Responses.sh

set -o posix

# This file was generated by dsh.

# This file defines the App Packages configuration variables. This script MUST be
# sourced from Responses.sh, Requests.sh, and OutputComponents.sh so they all use
# the same configuration variables.

app_name="APP_NAME"
domain="DOMAIN"
development_port="PORT"
version="VERSION"
version_date="DATE"
developers=( "Dev 1" "Dev 2") # Modify this as needed
declare -A dependencies
dependencies=([version]=AppName [Version]=AppName2 ["versioN"]="AppName3")
bug_contact="EMAIL"
documentation="DOCUMENTATION_SOURCE"
config_locked="LOCK_CONFIG"
description="DESCRIPTION"
