#!/bin/bash
# APP_NAME | Responses.sh

set -o posix

# This file was generated by dsh.
# This file defines the APP_NAME App Package's configuration variables.
# For more information about this file use: dsh -h -n AppPackage config.sh

######################## Configuration Settings ########################

app_name="APP_NAME"

bug_contact="contact not provided"

config_locked="0"

declare -A dependencies
dependencies=()

description="The APP_NAME App was developed for the Darling Data Management System."

developers=()

development_port="PORT"

documentation="DOCUMENTATION_SOURCE"

domain="DOMAIN"

license="MIT"

version="0.0.0"

version_date="unknown"

