#!/bin/bash
# APP_NAME | Responses.sh

set -o posix

# This file was generated by dsh.

# This file defines the App Packages configuration variables. This script MUST be
# sourced from Responses.sh, Requests.sh, and OutputComponents.sh so they all use
# the same configuration variables.

app_name="APP_NAME"
domain="DOMAIN"
development_port="PORT"
version="0.0.0"
version_date="1610419164"
developers=""
dependencies=""
bug_contact="someemail@example.com"
documentation="self-documented"
config_locked="0"
description="DESCRIPTION"
