<?php

/** APP_NAME | DYNAMIC_OUTPUT_COMPONENT_NAME.php */

 $appComponentsFactory->buildDynamicOutputComponent(
    'DYNAMIC_OUTPUT_COMPONENT_NAME',
    'DYNAMIC_OUTPUT_COMPONENT_CONTAINER',
    DYNAMIC_OUTPUT_COMPONENT_POSITION,
    'APP_NAME',
    'DYNAMIC_OUTPUT_FILE'
);

