#!/bin/bash
# APP_NAME | OutputComponents.sh

set -o posix

# This file was generated by dsh.

# Use this file to define the OutputComponents for the App.
# Only OutputComponents, and DynamicOutputComponents should be defined in this file.

# OutputComponents are used by the Darling Data Managment System to define static output.

# DynamicOutputComponents are used by the Darling Data Managment System to define output that is generatd from a file.

# For help with dsh use `dsh --help`
# For brief help with dsh use `dsh --help flags`

# Additional documentation can be found on GitHub at https://github.com/sevidmusic/DarlingDataManagementSystem

# Example OutputComponent:
# dsh --new OutputComponent "${app_name}" OutputComponentName OutputComponentContainer 0 "Output"

# Example DynamicOutputComponent:
# dsh --new DynamicOutputComponent "${app_name}" DynamicOutputComponentName DynamicOutputComponentContainer 0 "FileName.php"

