#!/bin/bash
# APP_NAME | Responses.sh

set -o posix

# This file was generated by dsh.

# Use this file to define the Responses for the App.
# Only Responses, and GlobalResponses should be defined in this file.

# Responses are used by the Darling Data Managment System to determine which
# Output Componetns should load for which Requests.

# GlobalResponses are used by the Darling Data Management System to determine which
# Output Components should load for all Requests.

# For help with dsh use `dsh --help`
# For brief help with dsh use `dsh --help flags`

# Additional documentation can be found on GitHub at https://github.com/sevidmusic/DarlingDataManagementSystem

# Example Response:
# dsh --new Response "${app_name}" ResponseName 0

# Example GlobalResponse:
# dsh --new GlobalResponse "${app_name}" GlobalResponseName 3

