<?php

namespace roady\interfaces\component;

use roady\interfaces\component\SwitchableComponent as SwitchableComponentInterface;
use roady\interfaces\primary\Positionable as PositionableInterface;

/**
 * An OutputComponent is a SwitchableComponent that can generate output.
 *
 * Additionally, an OutputComponent has a numeric position that
 * can be incremented or decremented.
 */
interface OutputComponent extends SwitchableComponentInterface, PositionableInterface
{

    /**
     * Returns the output generated by this OutputComponent.
     *
     * @return string The output of this OutputComponent.
     */
    public function getOutput(): string;

}
