#!/bin/bash

set -o posix

currentDirectoryPath() {
    local CURRENT_DIRECTORY
    CURRENT_DIRECTORY="${BASH_SOURCE[0]}"
    # Resolve symlynks
    while [ -h "$CURRENT_DIRECTORY" ]; do
      DIR="$(cd -P "$(dirname "$CURRENT_DIRECTORY")" >/dev/null 2>&1 && pwd)"
      CURRENT_DIRECTORY="$(readlink "$CURRENT_DIRECTORY")"
      [[ $CURRENT_DIRECTORY != /* ]] && CURRENT_DIRECTORY="$DIR/$CURRENT_DIRECTORY" # if $CURRENT_DIRECTORY was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    printf "%s" "${CURRENT_DIRECTORY}"
}

setupPaths() {
    PATH_TO_DSH_DIR="$(cd -P "$(dirname "$(currentDirectoryPath)")" >/dev/null 2>&1 && pwd)"
    PATH_TO_DSHUI="${PATH_TO_DSH_DIR}/dshui.sh"
    PATH_TO_DSH_FUNCTIONS="${PATH_TO_DSH_DIR}/dshfunctions.sh"
    PATH_TO_DDMS="${PATH_TO_DSH_DIR/dsh\//}"
}

setupVars() {
    TEST_FILE_NAME="${1}"
    TEST_GROUP_NAME="${2}"
}

loadLibrary() {
    [[ ! -f "${1}" ]] && printf "\n\n\e[33mError! Failed to load ${1}!\e[0m\n\n" && exit 1
    . "${1}"
}

runTestFile() {
    [[ -f "${PATH_TO_DSH_DIR}/dshUnitTests/${1}" ]] && "${PATH_TO_DSH_DIR}/dshUnitTests/${1}" "${2}"
}

setupPaths

setupVars "${1}" "${2}"

loadLibrary "${PATH_TO_DSH_FUNCTIONS}"

loadLibrary "${PATH_TO_DSHUI}"

runTestFile "${TEST_FILE_NAME}" "${TEST_GROUP_NAME}"

# Assertion Function Definitions #

assertSuccess() {
    { ${1} &> /dev/null; } && notifyUser "${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR} ran without error ${SUCCESSCOLOR}:)" 0 'dontClear' && return
    notifyUser "${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR}: ${ERRORCOLOR}Failed asserting success. An error occured, run ${CLEAR_ALL_TEXT_STYLES}${HIGHLIGHTCOLOR}${1}${CLEAR_ALL_TEXT_STYLES}${ERRORCOLOR} manually to see error messages." 0 'dontClear'
}

assertError() {
    { ${1} &> /dev/null; } && notifyUser "${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR}: ${ERRORCOLOR}Failed asserting error. An error did not occur even though one was was expected, run ${CLEAR_ALL_TEXT_STYLES}${HIGHLIGHTCOLOR}${1}${CLEAR_ALL_TEXT_STYLES}${ERRORCOLOR} manually to see actual output." 0 'dontClear' && return
    notifyUser "${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR} triggered an error as expected ${SUCCESSCOLOR}:)" 0 'dontClear'
}

assertDirectroyExists() {
    [[ ! -d "${1}" ]] && notifyUser "${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR}: ${ERRORCOLOR}Failed asserting that the directory ${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR} exists" 0 'dontClear' && return
    notifyUser "The ${HIGHLIGHTCOLOR}${1}${NOTIFYCOLOR} directory exists ${SUCCESSCOLOR}:)" 0 'dontClear'
}
