<?php

namespace DarlingDataManagementSystem\classes\utility;

use DarlingDataManagementSystem\abstractions\utility\ReflectionUtility as ReflectionUtilityAbstraction;
use DarlingDataManagementSystem\interfaces\utility\ReflectionUtility as ReflectionUtilityInterface;

class ReflectionUtility extends ReflectionUtilityAbstraction implements ReflectionUtilityInterface
{
}
