<?php

$appComponentsFactory->buildGlobalResponse(
    'CloseBodyCloseHtml',
    9999999999999999,
    $appComponentsFactory->buildStandardUITemplate(
        'StandardUITemplate',
        'Components',
        0,
        $appComponentsFactory->buildOutputComponent(
            'OutputComponent',
            'Components',
            '',
            0
        ),
    ),
    $appComponentsFactory->buildOutputComponent(
        'ClosingBodyTag',
        'Components',
        '</body>',
        0
    ),
    $appComponentsFactory->buildOutputComponent(
        'OpeningHtmlTag',
        'Components',
        '</html>',
        0.1
    ),
);

