<?php

use DarlingCms\classes\component\Crud\ComponentCrud;
use DarlingCms\classes\component\Driver\Storage\Standard;
use DarlingCms\classes\component\OutputComponent;
use DarlingCms\classes\component\Template\UserInterface\StandardUITemplate;
use DarlingCms\classes\component\Web\App;
use DarlingCms\classes\component\Web\Routing\Request;
use DarlingCms\classes\component\Web\Routing\Response;
use DarlingCms\classes\primary\Positionable;
use DarlingCms\classes\primary\Storable;
use DarlingCms\classes\primary\Switchable;

ini_set('display_errors', true);
require '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$tempNameLocationContainer = 'TEMP';

/***********/
/*** App ***/
/***********/
$domain = new Request(
    new Storable(
        'WorkingDemoAppDomain',
        $tempNameLocationContainer,
        $tempNameLocationContainer
    ),
    new Switchable()
);
$domain->import(['url' => 'http://192.168.33.10/']);
$app = new App($domain, new Switchable());

/****************/
/*** Requests ***/
/****************/
$workingDemoStoredRequest = new Request(
    new Storable(
        'WorkingDemoStoredRequest',
        $app->getLocation(),
        'Requests'
    ),
    new Switchable()
);

$workingDemoStoredRequest->import(['url' => 'http://192.168.33.10/index.php?WorkingDemo']);

$indexRequest = new Request(
    new Storable(
        'IndexRequest',
        $app->getLocation(),
        'Requests'
    ),
    new Switchable()
);
$indexRequest->import(['url' => 'http://192.168.33.10/index.php']);

$rootRequest = new Request(
    new Storable(
        'RootRequest',
        $app->getLocation(),
        'Requests'
    ),
    new Switchable()
);
$rootRequest->import(['url' => 'http://192.168.33.10/']);


/***** OUTPUT COMPONENTS *****/
/**
 * Doctype
 */
$doctype = new OutputComponent(
    new Storable(
        "Doctype",
        $app->getLocation(),
        'Output'
    ),
    new Switchable(),
    new Positionable(0)
);
$doctype->import(['output' => '<!DOCTYPE html><html lang="en">']);

/**
 * Html <head>
 */
$htmlHead = new OutputComponent(
    new Storable(
        "HtmlHead",
        $app->getLocation(),
        'Output'
    ),
    new Switchable(),
    new Positionable(1)
);
$htmlHead->import(
    [
        'output' => file_get_contents(__DIR__ . '/html/HtmlHeadCommon.html')
    ]
);

/**
 * Html <body>
 */
$workingDemoHtmlBody = new OutputComponent(
    new Storable(
        "WorkingDemoHtmlBody",
        $app->getLocation(),
        'Output'
    ),
    new Switchable(),
    new Positionable(2)
);

ob_start();
require_once(__DIR__ . DIRECTORY_SEPARATOR . 'html/WorkingDemoHtmlBody.php');
$workingDemoHtml = ob_get_clean();
$workingDemoHtmlBody->import(
    [
        'output' => $workingDemoHtml
    ]
);

$indexHtmlBody = new OutputComponent(
    new Storable(
        "IndexHtmlBody",
        $app->getLocation(),
        'Output'
    ),
    new Switchable(),
    new Positionable(2)
);
$indexHtmlBody->import(['output' => '
    <body class="gradientBg">
    <div class="genericContainer successText">
        <p>Welcome</p>
        <p>Use the menu below to navigate around</p>
        <ul>
            <li><a href="http://192.168.33.10/index.php">Home</a></li>
            <li><a href="http://192.168.33.10/">Root</a></li>
            <li><a href="http://192.168.33.10/WorkingDemo.php">Demo</a></li>
            <li><a href="http://192.168.33.10/index.php?WorkingDemo">Installed WorkingDemo App</a></li>
        </ul>
    </div>
    </body>
'
]);


$finalOutput = new OutputComponent(
    new Storable(
        "FinalHtmlOutput",
        $app->getLocation(),
        'Output'
    ),
    new Switchable(),
    new Positionable(3)
);
$finalOutput->import(['output' => '</html><!-- this html was generated by Darling Data Management System Components configured by the WorkingDemo App -->']);

/***** StandardUITemplates *****/
$standardUITemplate = new StandardUITemplate(
    new Storable(
        'StandardUITemplate',
        $app->getLocation(),
        'Templates'
    ),
    new Switchable(),
    new Positionable(0)
);
// All the OutputComponents defined at the moment are same type so we
// only new to call addType() on one of them, if there were different
// types of OutputComponents used then each type would need to be added
// to be represented in the Template.
$standardUITemplate->addType($finalOutput);


// Responses
$workingDemoStoredResponse = new Response(
    new Storable(
        $app->getLocation() . 'Response',
        $app->getLocation(),
        Response::RESPONSE_CONTAINER
    ),
    new Switchable()
);
$workingDemoStoredResponse->addRequestStorageInfo($workingDemoStoredRequest);
$workingDemoStoredResponse->addTemplateStorageInfo($standardUITemplate);
$workingDemoStoredResponse->addOutputComponentStorageInfo($doctype);
$workingDemoStoredResponse->addOutputComponentStorageInfo($htmlHead);
$workingDemoStoredResponse->addOutputComponentStorageInfo($workingDemoHtmlBody);
$workingDemoStoredResponse->addOutputComponentStorageInfo($finalOutput);

$indexResponse = new Response(
    new Storable(
        'IndexResponse',
        $app->getLocation(),
        Response::RESPONSE_CONTAINER
    ),
    new Switchable()
);
$indexResponse->addRequestStorageInfo($indexRequest);
$indexResponse->addRequestStorageInfo($rootRequest);
$indexResponse->addTemplateStorageInfo($standardUITemplate);
$indexResponse->addOutputComponentStorageInfo($doctype);
$indexResponse->addOutputComponentStorageInfo($htmlHead);
$indexResponse->addOutputComponentStorageInfo($indexHtmlBody);
$indexResponse->addOutputComponentStorageInfo($finalOutput);


$componentCrud = new ComponentCrud(
    new Storable(
        'Crud',
        $app->getLocation(),
        'Crud'
    ),
    new Switchable(),
    new Standard(
        new Storable(
            'StorageDriver',
            $app->getLocation(),
            'StorageDrivers'
        ),
        new Switchable()
    )
);

$components = [
    $app,
    $workingDemoStoredRequest,
    $indexRequest,
    $rootRequest,
    $workingDemoStoredResponse,
    $indexResponse,
    $standardUITemplate,
    $doctype,
    $htmlHead,
    $workingDemoHtmlBody,
    $indexHtmlBody,
    $finalOutput
];

foreach ($components as $component) {
    printf(
        "<p>Saving component %s to location <span style='color: purple;'>%s</span> in container <span style='color: green;'>%s</span></p>",
        $component->getName(),
        $component->getLocation(),
        $component->getContainer()
    );
    printf(
        "%s",
        ($componentCrud->create($component) === true ? "<p style=\"color: green;\">Saved successfully</p>" : "<p style=\"color: red;\">The component could not be saved</p>")
    );
}

